[build]
  publish = "."
  command = "node build.js && echo 'Force rebuild 2025-01-27'"
  functions = "netlify/functions"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  PYTHON_VERSION = "3.9"

[context.production]
  environment = { NODE_ENV = "production", MIDAS_ENV = "production" }

[context.production.processing]
  skip_processing = false

[context.production.processing.css]
  bundle = true
  minify = true

[context.production.processing.js]
  bundle = true
  minify = true

[context.production.processing.html]
  pretty_urls = true

# API Routes for all Phase 9 features
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth-:splat"
  status = 200

[[redirects]]
  from = "/api/inventory/*"
  to = "/.netlify/functions/inventory-:splat"
  status = 200

[[redirects]]
  from = "/api/booking/*"
  to = "/.netlify/functions/booking-:splat"
  status = 200

[[redirects]]
  from = "/api/payment/*"
  to = "/.netlify/functions/payment-:splat"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin-:splat"
  status = 200

[[redirects]]
  from = "/api/ai/*"
  to = "/.netlify/functions/ai-:splat"
  status = 200

[[redirects]]
  from = "/api/loyalty/*"
  to = "/.netlify/functions/loyalty-:splat"
  status = 200

[[redirects]]
  from = "/api/blockchain/*"
  to = "/.netlify/functions/blockchain-:splat"
  status = 200

[[redirects]]
  from = "/api/virtual-tours/*"
  to = "/.netlify/functions/virtual-tours-:splat"
  status = 200

[[redirects]]
  from = "/api/analytics/*"
  to = "/.netlify/functions/analytics-:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA Fallback
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(self), payment=(self)"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

# Static Assets Caching
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Vary = "Accept-Encoding"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# API Headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Access-Control-Allow-Origin = "https://midasthelifestyle.com"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    Access-Control-Max-Age = "86400"

# PWA Manifest
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Content-Type = "application/manifest+json"

# Service Worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Content-Type = "application/javascript"
